# Setup
title:        "How to get on the web: Hack the TriCo 2018"
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      "/learning-flask"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Nabil Kashyap
  url:        http://ds.swarthmore.edu

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown